/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as elasticTokenSol from "./ElasticToken.sol";
export type { elasticTokenSol };
import type * as mocks from "./mocks";
export type { mocks };
