/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ReentrancyAttacker,
  ReentrancyAttackerInterface,
} from "../../../mocks/ReentrancyAttacker.sol/ReentrancyAttacker";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "attack",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [
      {
        internalType: "contract IElasticToken",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x60806040526000805460ff60a01b1916905534801561001d57600080fd5b506040516102c73803806102c783398101604081905261003c91610061565b600080546001600160a01b0319166001600160a01b0392909216919091179055610091565b60006020828403121561007357600080fd5b81516001600160a01b038116811461008a57600080fd5b9392505050565b610227806100a06000396000f3fe60806040526004361061002d5760003560e01c80639e5faafc146100ec578063fc0c546a146100f457600080fd5b366100e757600054600160a01b900460ff16156100e5576000805460ff60a01b198116825560408051636d6bd72d60e11b81526004810191909152600360448201526242544360e81b606482015260248101929092526001600160a01b03169063dad7ae5a90670de0b6b3a76400009060840160206040518083038185885af11580156100be573d6000803e3d6000fd5b50505050506040513d601f19601f820116820180604052508101906100e391906101d8565b505b005b600080fd5b6100e5610130565b34801561010057600080fd5b50600054610114906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b60008054600160a01b60ff60a01b19821617825560408051636d6bd72d60e11b81526004810191909152600360448201526242544360e81b606482015260248101929092526001600160a01b03169063dad7ae5a90670de0b6b3a76400009060840160206040518083038185885af11580156101b0573d6000803e3d6000fd5b50505050506040513d601f19601f820116820180604052508101906101d591906101d8565b50565b6000602082840312156101ea57600080fd5b505191905056fea26469706673582212209eb537bf8261edde48862f9e98343ce13fda1790e4b38a716c4561b04a93138164736f6c63430008130033";

type ReentrancyAttackerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReentrancyAttackerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReentrancyAttacker__factory extends ContractFactory {
  constructor(...args: ReentrancyAttackerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _token: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_token, overrides || {});
  }
  override deploy(
    _token: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_token, overrides || {}) as Promise<
      ReentrancyAttacker & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReentrancyAttacker__factory {
    return super.connect(runner) as ReentrancyAttacker__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReentrancyAttackerInterface {
    return new Interface(_abi) as ReentrancyAttackerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReentrancyAttacker {
    return new Contract(address, _abi, runner) as unknown as ReentrancyAttacker;
  }
}
